### ISSUE TITLE
Eclipse 2022-12 WTP nature not enabled when importing "war" Maven projects

### ISSUE THREAD

**Issue by eliasbalasis** [eclipse-m2e/m2e-wtp#19]
In Eclipse 20222-12, which is equipped with m2e 2.1.2, importing a "war" Maven artifact having <m2e.wtp.activation>true</m2e.wtp.activation> does not equip the imported project with WTP natures anymore.

This works in Eclipse 2022-06 though, which is equipped with m2e 1.20.1

**Comment by mickaelistria** [comment]
OK, I transferred issue to m2e-wtp.
Would you be able to submit a test case as a PR here to include it in the build and that would showcase the issue?

**Comment by eliasbalasis** [comment]
This is not reproducible in more recent versions of "Eclipse IDE for Enterprise Java and Web Developers" package.
