### ISSUE TITLE
When will Eclipse IDE support Jakarta Faces 3.x and above? It seems the Eclipse IDE can only support JSF 2.3 and javax.*

### ISSUE THREAD

**Issue by simk2024** [eclipse-m2e/m2e-wtp#33]
Afaik the most recent Eclipse IDE (4.32.0) still has no support for any JSF Version beyond 2.3.

There seems to be at least one ticket in old bugtracker, but with no useable information of when (or even if) this will be added in the future. (https://bugs.eclipse.org/bugs/show_bug.cgi?id=577596)

**Comment by mickaelistria** [comment]
Support for Jakarta Faces is not provided by m2e, but by Eclipse Web Tools Platform (WTP). Please get in touch with WTP support channels for this question.
